CREATE TABLE  E_BOOK 
   (	CALLNO VARCHAR(40), 
	NAME VARCHAR(4000), 
	AUTHOR VARCHAR(4000), 
	PUBLISHER VARCHAR(4000), 
	QUANTITY VARCHAR(1000), 
	ISSUED DATE, 
	 CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO)
   )
/
CREATE TABLE  E_LIBRARIAN 
   (	ID VARCHAR(40), 
	NAME VARCHAR(4000), 
	PASSWORD VARCHAR(4000), 
	EMAIL VARCHAR(4000), 
	MOBILE VARCHAR(400), 
	 CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID)
   )
/
Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE  E_ISSUEBOOK 
   (	CALLNO VARCHAR(4000) NOT NULL , 
	STUDENTID VARCHAR(4000) NOT NULL , 
	STUDENTNAME VARCHAR(4000), 
	STUDENTMOBILE INT(40), 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(4000)
   )
/


